name: omg it's mgp!
base_url: http://omgitsmgp.com
markdown: redcarpet
pygments: true
permalink: pretty

redcarpet:
  extensions: [no_intra_emphasis, autolink, strikethrough, superscript, underline, smart]
