name: omg it's mgp!
base_url: http://omgitsmgp.com
markdown: redcarpet
pygments: true
permalink: pretty
enable_disqus: true
enable_ga: true

redcarpet:
  extensions: [no_intra_emphasis, autolink, strikethrough, superscript, underline, smart]
