name: omg it's mgp!
base_url: http://omgitsmgp.com
markdown: redcarpet
permalink: pretty

enable_analytics: true
enable_disqus: true
enable_sharing: true

redcarpet:
  extensions: [no_intra_emphasis, autolink, strikethrough, superscript, underline, smart]
